pipeline:
  name: k8s-helm-1
  identifier: k8shelm
  projectIdentifier: Labs
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: k8shelm-1
        identifier: k8shelm
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8shelm
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  manifests:
                    - manifest:
                        identifier: k8shelm
                        type: HelmChart
                        spec:
                          chartVersion: <+input>
                  variables:
                    - name: onlySecretDeployment
                      type: String
                      default: "true"
                      value: <+input>.default(true).allowedValues(true,false)
          environment:
            environmentRef: Lab
            deployToAll: false
            infrastructureDefinitions:
              - identifier: cxelab
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: K8sDryRun_1
                  identifier: K8sDryRun_1
                  spec:
                    encryptYamlOutput: false
                  timeout: 10m
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
