pipeline:
  name: stepgrouptest
  identifier: stepgrouptest
  projectIdentifier: Labs
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: stepgroup
        identifier: stepgroup
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: stepgroup
                  identifier: stepgroup
                  steps:
                    - step:
                        type: GitClone
                        name: GitClone_1
                        identifier: GitClone_1
                        spec:
                          connectorRef: org.githubthroughdelegate
                          repoName: demo-repo
                          build:
                            type: branch
                            spec:
                              branch: main
                    - step:
                        type: Run
                        name: Run_1
                        identifier: Run_1
                        spec:
                          connectorRef: podinfodockerconnectorpublish
                          image: nginx:latest
                          shell: Sh
                          command: |-
                            echo "Install JQ and set environment variables"
                            curl -L -o /usr/local/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64 \
                                && chmod +x /usr/local/bin/jq
                                
                            #source jq -r '.[] | "export \(.name)=\(.value)"' /harness/demo-repo/env.json
                            eval "$(jq -r '.[] | "export \(.name)=\(.value)"' /harness/demo-repo/env.json)"

                            #export output=$(jq -r '.[] | "\(.name): \(.value)"' /harness/demo-repo/env.json)
                            #export output=$(jq -r '.[] | "\(.name): \(.value)\\n"' /harness/demo-repo/env.json)
                            export output=$(jq -r '.[] | "  \(.name): \(.value)"' /harness/demo-repo/env.json)
                            env

                            apt update
                            apt install procps -y

                            sleep 10000
                          envVariables:
                            test: value1
                            test2: value2
                          outputVariables:
                            - name: ENV_VARIABLE
                              type: String
                              value: output
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: k8sdemoconnector
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
    - stage:
        name: run-tests
        identifier: runtests
        description: ""
        type: Pipeline
        spec:
          org: Customer_Experience
          pipeline: stepgrouptest_Clone
          project: Labs
          inputs:
            identifier: stepgrouptest_Clone
            stages:
              - stage:
                  identifier: stepgroup
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - stepGroup:
                            identifier: stepgroup
                            steps:
                              - step:
                                  identifier: Run_2
                                  type: Run
                                  spec:
                                    envVariables: <+input>
            variables:
              - name: pipelinevariable
                type: String
                value: <+input>
  variables:
    - name: pipelinevariable
      type: String
      description: ""
      required: false
      value: <+input>
