pipeline:
  name: stepgrouptest
  identifier: stepgrouptest
  projectIdentifier: Labs
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: stepgroup
        identifier: stepgroup
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: stepgroup
                  identifier: stepgroup
                  steps:
                    - step:
                        type: GitClone
                        name: GitClone_1
                        identifier: GitClone_1
                        spec:
                          connectorRef: org.githubthroughdelegate
                          repoName: demo-repo
                          build:
                            type: branch
                            spec:
                              branch: main
                    - parallel:
                        - step:
                            type: Run
                            name: Run_1
                            identifier: Run_1
                            spec:
                              connectorRef: podinfodockerconnectorpublish
                              image: nginx:latest
                              shell: Sh
                              command: |-
                                echo "Install JQ and set environment variables"
                                curl -L -o /usr/local/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64 \
                                    && chmod +x /usr/local/bin/jq
                                    
                                #source jq -r '.[] | "export \(.name)=\(.value)"' /harness/demo-repo/env.json
                                eval "$(jq -r '.[] | "export \(.name)=\(.value)"' /harness/demo-repo/env.json)"

                                export output=$(jq -r '.[] | "\(.name): \(.value)"' /harness/demo-repo/env.json)

                                env

                                apt update
                                apt install procps -y

                                #sleep 10000
                              envVariables:
                                test: value1
                                test2: value2
                              outputVariables:
                                - name: ENV_VARIABLE
                                  type: String
                                  value: output
                        - step:
                            type: Run
                            name: Run_2
                            identifier: Run_2
                            spec:
                              connectorRef: podinfodockerconnectorpublish
                              image: nginx:latest
                              shell: Sh
                              envVariables:
                                environment_variable_1: value1
                                environment_variable_2: value2
                            when:
                              stageStatus: Success
                              condition: "false"
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: k8sdemoconnector
              - stepGroup:
                  name: run-tests
                  identifier: runtests
                  steps:
                    - step:
                        type: Run
                        name: Run_4
                        identifier: Run_4
                        spec:
                          connectorRef: podinfodockerconnectorpublish
                          image: nginx:latest
                          shell: Sh
                          envVariables: <+pipeline.stages.stepgroup.spec.execution.steps.stepgroup.steps.Run_1.output.outputVariables.ENV_VARIABLE>
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: k8sdemoconnector
                      namespace: gowri
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
  variables:
    - name: pipelinevariable
      type: String
      description: ""
      required: false
      value: <+input>
