pipeline:
  name: cd-test
  identifier: cdtest
  projectIdentifier: Labs
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: cd
        identifier: cd
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginxservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: nginximage
                          type: DockerRegistry
                          spec:
                            tag: <+input>
                  variables:
                    - name: test_variable
                      type: String
                      value: <+input>
                    - name: secertvalue
                      type: Secret
                      value: <+input>
                    - name: deploy_mode
                      type: String
                      default: none
                      value: <+input>.default(none).selectOneFrom(blue,green,none)
          environment:
            environmentRef: Lab
            deployToAll: false
            infrastructureDefinitions:
              - identifier: cxelab
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 11m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
